# Example file for a Drupal-based setup.
version: '3'
services:

  web:
    image: reload/drupal-apache-fpm
    ports:
      - '80'
    depends_on:
      - fpm
    volumes:
      - './:/var/www/web'

  fpm:
    image: reload/drupal-php7-fpm:7.1
    ports:
      - '9000'
    depends_on:
      - db
    working_dir: /var/www/web
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"

  db:
    image: reload/db-datadir:spejderdk-latest-fulldb
    ports:
      - '3306'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025'
