# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install `drupal-check`
          command: |
            mkdir -p ~/bin
            curl --silent --output ~/bin/drupal-check -O -L https://github.com/mglaman/drupal-check/releases/latest/download/drupal-check.phar
            chmod +x ~/bin/drupal-check
            ~/bin/drupal-check --version

      - run:
          name: Install PHP Extensions
          command: |
            sudo -E apt-get install -y libpng-dev
            sudo -E docker-php-ext-install gd

      - run:
          name: Validate composer.json and composer.lock
          command: composer validate --no-check-all --no-check-publish

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Composer install dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      - run:
          name: Run PHP Unit tests
          command: vendor/bin/phpunit

      - run:
          name: Analysis and check for deprecated code
          command: |
            status=0
            mkdir -p ~/test-results/analysis ~/test-results/deprecations
            (~/bin/drupal-check --analysis --format=junit --no-progress --no-interaction -- web/modules/custom/ > ~/test-results/analysis/modules.xml) || status=1
            (~/bin/drupal-check --analysis --format=junit --no-progress --no-interaction -- web/themes/custom/ > ~/test-results/analysis/themes.xml) || status=1
            (~/bin/drupal-check --deprecations --format=junit --no-progress --no-interaction -- web/modules/custom/ > ~/test-results/deprecations/modules.xml) || status=1
            (~/bin/drupal-check --deprecations --format=junit --no-progress --no-interaction -- web/themes/custom/ > ~/test-results/deprecations/themes.xml) || status=1
            exit $status

      - store_test_results:
          path: ~/test-results
