# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

orbs:
  backstop: reload/backstop@2
  dais: reload/dais@1
  drupal-check: reload/drupal-check@1

executors:
  backstop-dais:
    docker:
      - image: circleci/php:7.3-cli-node-browsers

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.3-apache-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install PHP Extensions
          command: |
            sudo -E apt-get install -y libpng-dev
            sudo -E docker-php-ext-install gd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Composer install dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Run PHP Unit tests
          command: vendor/bin/phpunit

workflows:
  version: 2

  'Composer build and phpunit':
    jobs:
      - build:
          name: Composer build and phpunit
  'Drupal Check':
    jobs:
      - drupal-check/drupal-check:
          name: Drupal Check
  'Visual regression tests':
    jobs:
      - backstop/visual-test:
          name: Visual regression tests
          context: BackstopJS Report Github Status
          executor: backstop-dais
          before_test:
            - dais/wait:
                files: backstop.json
          filters:
            branches:
              ignore:
                - master
