---
version: "2"
checks:
  argument-count:
    config:
      threshold: 6
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        # Standard configuration.
        - TODO
        - FIXME
        - HACK
        - BUG
        # Doxygen variants.
        - '@todo'
        - '@fixme'
  phpcodesniffer:
    enabled: true
    config:
      standard: Drupal,DrupalPractice
  scss-lint:
    enabled: true
exclude_patterns:
  - web/autoload.php
  - web/index.php
  - web/sites
  - scripts/composer/ScriptHandler.php
  - configuration
  # These aren't in the repo, but added for the sanity of someone
  # running CodeClimate locally.
  - build/
  - web/core
  - "**/node_modules/"
  - vendor/
  - "**/contrib/"
