# Example file for a PHP-based setup.
version: '3'
services:

  web:
    image: reload/drupal-apache-fpm:latest
    ports:
      - '80'
      - '443'
    depends_on:
      - fpm
    volumes:
      - './web/:/var/www/web:rw,cached'
      - './backend/vendor/:/var/www/vendor:ro,cached'

  fpm:
    image: reload/drupal-php7-fpm:7.2
    ports:
      - '9000'
    depends_on:
      - db
    working_dir: /var/www/web
    volumes:
      - './:/var/www:rw,cached'
      - './docker/my_init.d/install-cron.sh:/etc/my_init.d/install-cron.sh'
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"
      DRUSH_OPTIONS_URI: https://MY-PROJECT.docker

  db:
    image: reload/db-datadir:reloaddk-latest-fulldb
    ports:
      - '3306'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025'
