version: '3'

services:
  web:
    image: reload/drupal-apache-fpm:latest
    ports:
      - '80'
      - '443'
    depends_on:
      - fpm
    volumes:
      - 'projectroot:/var/www:rw,cached'
      - '${HOME}/.local/share/mkcert:/mkcert:ro'
      - '${HOME}/.local/share/dev_certificates:/cert:rw'
    environment:
      # Ensure dory redirects from http to https. We want to nag
      # people into doing development on valid HTTPS.
      HTTPS_METHOD: redirect
      # Ensure dory/nginx-proxy goes via port 80.
      VIRTUAL_PORT: '80'
      VIRTUAL_HOST: MY-PROJECT.docker
      MKCERT_DOMAINS: "MY-PROJECT.docker mail.MY-PROJECT.docker"

  fpm:
    image: reload/drupal-php7-fpm:7.2
    ports:
      - '9000'
    depends_on:
      - db
    working_dir: /var/www/web
    volumes:
      - 'projectroot:/var/www:rw,cached'
      - './docker/my_init.d/install-cron.sh:/etc/my_init.d/install-cron.sh'
    environment:
      PATH: '/var/www/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      PHP_SENDMAIL_PATH: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"
      DRUSH_OPTIONS_URI: https://MY-PROJECT.docker

  db:
    image: mariadb:10.3.9
    ports:
      - '3306'
    ## Below setup is for using a prebuild db-datadir.
    volumes:
      - 'db-data:/var/lib/mysql'
    depends_on:
      - db-data
    ## If you want af db-data dump use this image instead (and remove
    ## the volumes and depends_on).
    # image: eu.gcr.io/reloaddk-data/db-data:MY-PROJECT-latest

    ## If you want a clean database use the below environment instead
    ## (and remove the volumes and depends_on).
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: db
    #   MYSQL_USER: db
    #   MYSQL_PASSWORD: db

  db-data:
    image: eu.gcr.io/reloaddk-data/db-datadir:MY-PROJECT-latest
    volumes:
      - 'db-data:/var/lib/mysql'

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025'
    environment:
      VIRTUAL_HOST: mail.MY-PROJECT.docker

  npm:
    image: node:9-slim
    volumes:
      - 'projectroot:/var/www:rw,cached'
      - 'cache:/npm-cache'
    working_dir: /var/www/web/themes/custom/THEME_NAME
    environment:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      npm_config_cache: '/npm-cache/node'
    command: "npm start"

volumes:
  # NPM cache that survives docker-reset.sh
  cache:
  db-data:
  projectroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
